controllerManager:
  manager:
    image:
      repository: djkormo/adcs-issuer
      tag: latest
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

  replicas: 1

  environment:
    KUBERNETES_CLUSTER_DOMAIN: cluster.local
    ENABLE_WEBHOOKS: "false"
    ENABLE_DEBUG: "false"
  arguments:
    - --enable-leader-election=true
    - --cluster-resource-namespace=cert-manager
    - --zap-log-level=5
    - --disable-approved-check=false
  securityContext:
    runAsUser: 1000
  enabledWebHooks: false
  enabledCaCerts: false
  caCertsSecretName: ca-certificates
metricsService:
  enabled: true
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP

