crd:
  install: true

controllerManager:
  manager:
    image:
      repository: djkormo/adcs-issuer
      tag: 2.0.9
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi

  rbac:
    enabled: true
    serviceAccountName: adcs-issuer
    certManagerNamespace: cert-manager
    certManagerServiceAccountName: cert-manager 


  replicas: 1

  environment:
    KUBERNETES_CLUSTER_DOMAIN: cluster.local
    ENABLE_WEBHOOKS: "false"
    ENABLE_DEBUG: "false"
  arguments:
    enable-leader-election: "true"
    cluster-resource-namespace: adcs-issuer # must be the same as chart namespace
    zap-log-level: 5
    disable-approved-check: "false"

  securityContext:
    runAsUser: 1000

  enabledWebHooks: false
  enabledCaCerts: false
  caCertsSecretName: ca-certificates
metricsService:
  enabled: true
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP

simulator:
  enabled: true
  clusterIssuserName: adcs-sim-adcsclusterissuer
  deploymentName: adcs-sim-deployment
  configMapName: adcs-sim-configmap
  secretCertificateName: adcs-sim-certificate-secret
  secretName: adcs-sim-secret
  serviceName: adcs-sim-service 
  image:
    repository: djkormo/adcs-sim
    tag: 0.0.6

  environment:
    ENABLE_DEBUG: "false"

  arguments:
      dns: adcs-sim-service.adcs-issuer.svc,adcs2.example.com 
      ips: 10.10.10.1,10.10.10.2
      port: 8443

  containerPort: 8443
  servicePort: 8443

  livenessProbe:
    httpGet:
      path: /healthz
      port: 8443 # the same as containerPort
      scheme: HTTPS
    timeoutSeconds: 10
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8443 # the same as containerPort
      scheme: HTTPS
    timeoutSeconds: 20
    periodSeconds: 20
    initialDelaySeconds: 10

  podSecurityContext:
    runAsUser: 1000

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
      - all

  resources:

    limits:
      cpu: 100m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi  

  exampleCertificate:
    enabled: true 
    name: adcs-sim-certificate    
