apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --enable-leader-election=true
        - --cluster-resource-namespace=${POD_NAMESPACE}
        - --zap-log-level=5
        - --disable-approved-check=false
        command:
        - /manager
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.controllerManager.environment.KUBERNETES_CLUSTER_DOMAIN |quote}}
        - name: ENABLE_WEBHOOKS
          value: {{ .Values.controllerManager.environment.ENABLE_WEBHOOKS |quote }}
        - name: ENABLE_DEBUG
          value: {{ .Values.controllerManager.environment.ENABLE_DEBUG |quote }}
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        image: {{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag | default .Chart.AppVersion }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources: {{- toYaml .Values.controllerManager.manager.resources | nindent 10 }}
        volumeMounts:
         {{- if .Values.controllerManager.enabledWebHooks  }}
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        {{- end }}  
        {{- if .Values.controllerManager.enabledCaCerts  }}
        - mountPath: /etc/ssl/certs/ca-certificates.crt
          name: ca-certificates
          subPath: ca-certificates.crt
          readOnly: true
        {{- end }}  
      terminationGracePeriodSeconds: 10
      volumes:
      {{- if .Values.controllerManager.enabledWebHooks  }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      {{- end }}  
      
      {{- if .Values.controllerManager.enabledCaCerts  }}
      - name: ca-certificates
        secret:
          defaultMode: 420
          secretName: {{ .Values.controllerManager.caCertsSecretName| default "ca-certificates" }} 
      {{- end }}  