{{- if .Values.controllerManager.rbac.enabled  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.controllerManager.rbac.serviceAccountName }}
  
{{- end  }}  